use std::{fmt, str::FromStr};

use thiserror::Error;
use uuid::{Uuid, Variant, Version};

/// An opaque, time-sortable EmbedRelay identifier constrained to RFC 9562 UUIDv7.
///
/// EmbedRelay uses one identifier shape across tenant-scoped registry and audit
/// boundaries so callers cannot silently introduce random UUID versions or
/// implementation-specific identifiers. UUIDv7 keeps the identifier opaque
/// while placing the Unix-millisecond timestamp in the most significant bits,
/// which is suitable for ordered database keys without encoding tenant data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RelayIdentifier(Uuid);

impl RelayIdentifier {
    /// Generate a fresh RFC 9562 UUIDv7 using the process-local monotonic v7 context.
    ///
    /// UUIDs generated by this process are ordered by creation time. Callers
    /// must still treat the value as opaque and must not infer authorization or
    /// tenant identity from its timestamp component.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::now_v7())
    }

    /// Parse an externally supplied identifier and require the RFC 9562 UUIDv7 shape.
    ///
    /// # Errors
    ///
    /// Returns [`RelayIdentifierParseError`] for malformed UUID text, a UUID
    /// variant outside the RFC 9562 layout, or any UUID version other than v7.
    pub fn parse(value: &str) -> Result<Self, RelayIdentifierParseError> {
        value.parse()
    }

    /// Borrow the validated UUID value for storage adapters and protocol boundaries.
    #[must_use]
    pub const fn as_uuid(&self) -> &Uuid {
        &self.0
    }
}

impl Default for RelayIdentifier {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for RelayIdentifier {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl FromStr for RelayIdentifier {
    type Err = RelayIdentifierParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let uuid = Uuid::try_parse(value).map_err(|_| RelayIdentifierParseError::InvalidUuid)?;
        if uuid.get_variant() != Variant::RFC4122 {
            return Err(RelayIdentifierParseError::UnsupportedVariant);
        }
        if uuid.get_version() != Some(Version::SortRand) {
            return Err(RelayIdentifierParseError::UnsupportedVersion);
        }
        Ok(Self(uuid))
    }
}

/// Stable, non-reflecting reasons an external identifier cannot enter EmbedRelay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum RelayIdentifierParseError {
    /// The supplied text is not a syntactically valid UUID.
    #[error("identifier must be a valid UUID")]
    InvalidUuid,
    /// The UUID does not use the RFC 9562 / RFC 4122 variant bit layout.
    #[error("identifier must use the RFC 9562 UUID variant")]
    UnsupportedVariant,
    /// The UUID is syntactically valid but is not UUID version 7.
    #[error("identifier must use UUID version 7")]
    UnsupportedVersion,
}
